### ISSUE TITLE
Argo Client does not work with newer k8s client versions (>=v0.21.0)

### ISSUE THREAD

**Issue by nakumgaurav** [argoproj/argo-workflows#6750]
## Summary 
I am using the go-client for argo and here's how I defined it:

```
	opts := apiclient.Opts{
		ArgoServerOpts: apiclient.ArgoServerOpts{
			URL:                argoURI,
			Path:               argoPath,
			Secure:             true,
			InsecureSkipVerify: false,
			HTTP1:              true,
		},
		AuthSupplier: func() string {
			return ""
		},
	}
	argoCtx, argo, err := apiclient.NewClientFromOpts(opts)
	if err != nil {
		return "", err
	}
```

My go.mod file:
```
module ...

go 1.15

require (
	github.com/argoproj/argo-workflows/v3 v3.0.0
	github.com/go-logr/logr v0.4.0
	github.com/go-yaml/yaml v2.1.0+incompatible
	github.com/onsi/ginkgo v1.14.2
	github.com/onsi/gomega v1.10.4
	gitlab-odx.oracledx.com/cx-sales/code/titan/titan-core v0.2.0
	k8s.io/apimachinery v0.21.0
	k8s.io/client-go v0.21.0
	sigs.k8s.io/controller-runtime v0.7.2
)

```

What happened/what you expected to happen?
I need to use k8s go client version >= v0.21.0 but it seems the latest argo client is incompatible with the newer k8s versions. So

Running `go vet ./... `gives an error:

```# github.com/argoproj/argo-workflows/v3/util/kubeconfig
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.1.12\util\kubeconfig\kubeconfig.go:147:37: not enough arguments in call 
to exec.GetAuthenticator
        have (*api.ExecConfig)
        want (*api.ExecConfig, *clientauthentication.Cluster)
```

Clearly, the exec.GetAuthenticator function requires two arguments in the newer k8s client versions. Can a bug fix be released for this purpose? Alternately, how should I define my apiClient to be compatible with the latest k8s client? Would appreciate any pointers!

## Diagnostics

What Kubernetes provider are you using? 
Terraform

What version of Argo Workflows are you running? 
v0.3.12

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

Did this work in a previous version? I.e. is it a regression?
No

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by nakumgaurav** [comment]
EDIT: I tried with the master branch version of argo. This fixes the exec.GetAuthenticator error above, but raises a bunch of other issues:
```
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:52:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:64:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:72:8: cannot use ref("github.com/argoproj/argo-events/pkg/apis/common.Int64OrString") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:78:8: cannot use ref("github.com/argoproj/argo-events/pkg/apis/common.Amount") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:84:8: cannot use ref("github.com/argoproj/argo-events/pkg/apis/common.Amount") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:104:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:112:8: cannot use ref("k8s.io/api/core/v1.SecretKeySelector") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:118:8: cannot use ref("k8s.io/api/core/v1.SecretKeySelector") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:131:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:153:8: cannot use ref("k8s.io/apimachinery/pkg/apis/meta/v1.Time") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-events@v1.4.0\pkg\apis\common\openapi_generated.go:131:3: too many errors# github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:139:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:151:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:158:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Tar...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:163:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Non...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:168:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Zip...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:181:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:200:11: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Par...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:220:11: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Art...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:280:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.S3A...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:286:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Git...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
..\..\..\..\..\go\pkg\mod\github.com\argoproj\argo-workflows\v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f\pkg\apis\workflow\v1alpha1\openapi_generated.go:286:8: too many errors
```

**Comment by nakumgaurav** [comment]
@alexec I tried using the master branch version but this is still a problem with latest k8s client versions.

**Comment by ryanande** [comment]
I too am seeing the exact same error, any luck on identifying root cause or better context on what is happening @alexec ?

**Comment by alexec** [comment]
please can you compare your go.mod file and list differences

**Comment by alexec** [comment]
try removing everything but argo-workflows, then run `go mod download`

**Comment by nakumgaurav** [comment]
Now that I think about it, even using argo-wf v0.3.12 and following the process above would have worked, except that it would use k8s client v0.19.6 :)

**Comment by PrashantRaj18198** [comment]
> * Removed everything except argo-workflows from `go.mod`
> * `go mod download`
> * `go mod tidy `(this forces the k8s client to be at `v0.20.4`)
> * `go fmt ./... && go vet ./...`
This doesn't work for me, tried with latest version of argo-workflows and the above version also, in both cases I am getting some weird `openapi spec has wrong field type error`. Any clues for why this might be happening?
```console
# github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:139:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:151:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:158:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Tar...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:163:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Non...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:168:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Zip...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:181:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:200:11: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Par...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:220:11: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Art...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:280:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.S3A...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:286:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Git...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.0-rc3.0.20210916144414-7684ef4a0c5f/pkg/apis/workflow/v1alpha1/openapi_generated.go:286:8: too many errors
```

**Comment by cyx** [comment]
@PrashantRaj18198 are you still working on this?

**Comment by SVilgelm** [comment]
I have updated to `argo-workflows v3.2.5` and it installed `k8s.io/api v0.22.2`, but then I upgrade `github.com/influxdata/telegraf v1.21.1` and it brought `k8s.io/api v0.22.2`, so now I have totally same issue
```
# github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:139:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:151:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:158:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Tar...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:163:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Non...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:168:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Zip...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:181:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:200:11: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Par...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:220:11: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Art...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:280:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.S3A...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:286:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Git...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
vendor/github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1/openapi_generated.go:286:8: too many errors
```

**Comment by pradeep-av** [comment]
Anyone working on this @alexec @PrashantRaj18198 ? our project had a general dependency upgrade and most of the other dependencies need k8s client > 0.22 and this is the only dependency breaking.

**Comment by SVilgelm** [comment]
Does any one know, How to ping anyone of the argo-workflows maintainers?

**Comment by sarabala1979** [comment]
@SVilgelm are you using the latest v3.2.x CLI?

**Comment by SVilgelm** [comment]
@sarabala1979 I'm trying to update, but got same error:
```
22-02-08 16:39 % go get github.com/argoproj/argo-workflows/v3@latest
go: downloading github.com/argoproj/argo-workflows/v3 v3.2.8
go: downloading google.golang.org/grpc v1.44.0
go: downloading golang.org/x/sys v0.0.0-20220114195835-da31bd327af9
# github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:139:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:151:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:158:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Tar...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:163:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Non...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:168:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Zip...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:181:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:200:11: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Par...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:220:11: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Art...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:280:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.S3A...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:286:8: cannot use ref("github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.Git...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.2.8/pkg/apis/workflow/v1alpha1/openapi_generated.go:286:8: too many errors
```

**Comment by SVilgelm** [comment]
```
	k8s.io/kube-openapi v0.0.0-20211115234752-e816edb12b65 // indirect
```

**Comment by JPZ13** [comment]
@alexec We're running into this issue now. Is it cool if I take the upgrade to unblock us?

**Comment by alexec** [comment]
The PR is blocked on Argo Events PR. I'm waiting for @whynowy to review that PR, because I could not figure out how to get it to work nicely. Hoped he'd be able to bring new ideas to it.

**Comment by alexec** [comment]
Ugh. This is a massive tangel of dependiencies.
